-- MySQL Script generated by MySQL Workbench
-- Sat Sep 16 01:39:23 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PortalVoluntariado
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PortalVoluntariado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PortalVoluntariado` DEFAULT CHARACTER SET utf8 ;
USE `PortalVoluntariado` ;

-- -----------------------------------------------------
-- Table `PortalVoluntariado`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortalVoluntariado`.`Estado` ;

CREATE TABLE IF NOT EXISTS `PortalVoluntariado`.`Estado` (
  `ID_Estado` INT(2) NOT NULL AUTO_INCREMENT,
  `Nome` TEXT(30) NULL,
  PRIMARY KEY (`ID_Estado`),
  UNIQUE INDEX `ID_Estado_UNIQUE` (`ID_Estado` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PortalVoluntariado`.`Cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortalVoluntariado`.`Cidade` ;

CREATE TABLE IF NOT EXISTS `PortalVoluntariado`.`Cidade` (
  `ID_Cidade` INT(5) NOT NULL AUTO_INCREMENT,
  `Nome` TEXT(30) NULL,
  `ID_Estado` INT(2) NOT NULL,
  PRIMARY KEY (`ID_Cidade`),
  INDEX `fk_Cidade_Estado1_idx` (`ID_Estado` ASC),
  UNIQUE INDEX `ID_Cidade_UNIQUE` (`ID_Cidade` ASC),
  CONSTRAINT `fk_Cidade_Estado1`
    FOREIGN KEY (`ID_Estado`)
    REFERENCES `PortalVoluntariado`.`Estado` (`ID_Estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PortalVoluntariado`.`Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortalVoluntariado`.`Pessoa` ;

CREATE TABLE IF NOT EXISTS `PortalVoluntariado`.`Pessoa` (
  `CPF` INT(20) NOT NULL AUTO_INCREMENT,
  `Nome Completo` VARCHAR(45) NOT NULL,
  `DataNascimento` DATE DEFAULT NULL,
  `Email` VARCHAR(45) DEFAULT NULL,
  `Papel` TINYINT(2) DEFAULT NULL,
  `NomeDeUsuario` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(32) NOT NULL,
  `ID_Cidade` INT(7) DEFAULT NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `NomeDeUsuario_UNIQUE` (`NomeDeUsuario` ASC),
  INDEX `fk_Pessoa_Cidade1_idx` (`ID_Cidade` ASC),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC),
  CONSTRAINT `fk_Pessoa_Cidade1`
    FOREIGN KEY (`ID_Cidade`)
    REFERENCES `PortalVoluntariado`.`Cidade` (`ID_Cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PortalVoluntariado`.`Instituicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortalVoluntariado`.`Instituicao` ;

CREATE TABLE IF NOT EXISTS `PortalVoluntariado`.`Instituicao` (
  `ID_Instituicao` INT(5) NOT NULL AUTO_INCREMENT,
  `Nome` TEXT(50) NULL,
  `Descricao` TEXT(1000) NULL,
  `Rua` TEXT(30) NULL,
  `Complemento` TEXT(15) NULL,
  `Bairro` TEXT(30) NULL,
  `Email` TEXT(50) NULL,
  `Logotipo` LONGBLOB NULL,
  `Website` TEXT(80) NULL,
  `ID_Cidade` INT(5) NOT NULL,
  PRIMARY KEY (`ID_Instituicao`),
  INDEX `fk_Instituicao_Cidade1_idx` (`ID_Cidade` ASC),
  UNIQUE INDEX `ID_Instituicao_UNIQUE` (`ID_Instituicao` ASC),
  CONSTRAINT `fk_Instituicao_Cidade1`
    FOREIGN KEY (`ID_Cidade`)
    REFERENCES `PortalVoluntariado`.`Cidade` (`ID_Cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PortalVoluntariado`.`CausaDeInteresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortalVoluntariado`.`CausaDeInteresse` ;

CREATE TABLE IF NOT EXISTS `PortalVoluntariado`.`CausaDeInteresse` (
  `ID_Causa` INT(3) NOT NULL AUTO_INCREMENT,
  `Nome` TEXT(50) NULL,
  PRIMARY KEY (`ID_Causa`),
  UNIQUE INDEX `ID_Causa_UNIQUE` (`ID_Causa` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PortalVoluntariado`.`Pessoa-Instituicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortalVoluntariado`.`Pessoa-Instituicao` ;

CREATE TABLE IF NOT EXISTS `PortalVoluntariado`.`Pessoa-Instituicao` (
  `ID_Pessoa` INT(5) NOT NULL,
  `ID_Instituicao` INT(5) NOT NULL,
  PRIMARY KEY (`ID_Pessoa`, `ID_Instituicao`),
  INDEX `fk_Pessoa_has_Instituicao_Instituicao1_idx` (`ID_Instituicao` ASC),
  INDEX `fk_Pessoa_has_Instituicao_Pessoa_idx` (`ID_Pessoa` ASC),
  CONSTRAINT `fk_Pessoa_has_Instituicao_Pessoa`
    FOREIGN KEY (`ID_Pessoa`)
    REFERENCES `PortalVoluntariado`.`Pessoa` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_has_Instituicao_Instituicao1`
    FOREIGN KEY (`ID_Instituicao`)
    REFERENCES `PortalVoluntariado`.`Instituicao` (`ID_Instituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PortalVoluntariado`.`Pessoa-Causa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortalVoluntariado`.`Pessoa-Causa` ;

CREATE TABLE IF NOT EXISTS `PortalVoluntariado`.`Pessoa-Causa` (
  `ID_Pessoa` INT(5) NOT NULL,
  `ID_Causa` INT(3) NOT NULL,
  PRIMARY KEY (`ID_Pessoa`, `ID_Causa`),
  INDEX `fk_Pessoa_has_CausaDeInteresse_CausaDeInteresse1_idx` (`ID_Causa` ASC),
  INDEX `fk_Pessoa_has_CausaDeInteresse_Pessoa1_idx` (`ID_Pessoa` ASC),
  CONSTRAINT `fk_Pessoa_has_CausaDeInteresse_Pessoa1`
    FOREIGN KEY (`ID_Pessoa`)
    REFERENCES `PortalVoluntariado`.`Pessoa` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_has_CausaDeInteresse_CausaDeInteresse1`
    FOREIGN KEY (`ID_Causa`)
    REFERENCES `PortalVoluntariado`.`CausaDeInteresse` (`ID_Causa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PortalVoluntariado`.`Projeto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortalVoluntariado`.`Projeto` ;

CREATE TABLE IF NOT EXISTS `PortalVoluntariado`.`Projeto` (
  `ID_Projeto` INT(5) NOT NULL AUTO_INCREMENT,
  `Nome` TEXT(30) NULL,
  `Descricao` TEXT(1000) NULL,
  `Imagem` LONGBLOB NULL,
  `ID_Pessoa` INT(5) NOT NULL,
  `ID_Instituicao` INT(5) NOT NULL,
  PRIMARY KEY (`ID_Projeto`, `ID_Pessoa`, `ID_Instituicao`),
  INDEX `fk_Projeto_Pessoa-Instituicao1_idx` (`ID_Pessoa` ASC, `ID_Instituicao` ASC),
  UNIQUE INDEX `ID_Projeto_UNIQUE` (`ID_Projeto` ASC),
  CONSTRAINT `fk_Projeto_Pessoa-Instituicao1`
    FOREIGN KEY (`ID_Pessoa` , `ID_Instituicao`)
    REFERENCES `PortalVoluntariado`.`Pessoa-Instituicao` (`ID_Pessoa` , `ID_Instituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PortalVoluntariado`.`Vaga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortalVoluntariado`.`Vaga` ;

CREATE TABLE IF NOT EXISTS `PortalVoluntariado`.`Vaga` (
  `ID_Projeto` INT(5) NOT NULL,
  `ID_Vaga` INT(5) NOT NULL AUTO_INCREMENT,
  `Nome` TEXT(30) NULL,
  `Descricao` TEXT(512) NULL,
  `Pre-Requisito` TEXT(512) NULL,
  `Quantidade` INT(5) NULL,
  `ADistancia` TEXT(2) NULL,
  `Rua` TEXT(30) NULL,
  `Numero` INT(5) NULL,
  `Complemento` TEXT(15) NULL,
  `Bairro` TEXT(30) NULL,
  `Pontual` TINYINT NOT NULL,
  `ID_Cidade` INT(5) NOT NULL,
  PRIMARY KEY (`ID_Vaga`, `ID_Projeto`),
  INDEX `fk_Vaga_Cidade1_idx` (`ID_Cidade` ASC),
  INDEX `fk_Vaga_Projeto1_idx` (`ID_Projeto` ASC),
  UNIQUE INDEX `ID_Vaga_UNIQUE` (`ID_Vaga` ASC),
  CONSTRAINT `fk_Vaga_Cidade1`
    FOREIGN KEY (`ID_Cidade`)
    REFERENCES `PortalVoluntariado`.`Cidade` (`ID_Cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vaga_Projeto1`
    FOREIGN KEY (`ID_Projeto`)
    REFERENCES `PortalVoluntariado`.`Projeto` (`ID_Projeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PortalVoluntariado`.`Vaga-Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortalVoluntariado`.`Vaga-Pessoa` ;

CREATE TABLE IF NOT EXISTS `PortalVoluntariado`.`Vaga-Pessoa` (
  `ID_Pessoa` INT(5) NOT NULL,
  `ID_Vaga` INT(5) NOT NULL,
  `DataHora` DATETIME NULL,
  `Observacoes` TEXT(512) NULL,
  `PresencaConfirmada` TINYINT NULL,
  PRIMARY KEY (`ID_Pessoa`, `ID_Vaga`),
  INDEX `fk_Vaga_has_Pessoa_Pessoa1_idx` (`ID_Pessoa` ASC),
  CONSTRAINT `fk_Vaga_has_Pessoa_Vaga1`
    FOREIGN KEY (`ID_Vaga`)
    REFERENCES `PortalVoluntariado`.`Vaga` (`ID_Vaga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vaga_has_Pessoa_Pessoa1`
    FOREIGN KEY (`ID_Pessoa`)
    REFERENCES `PortalVoluntariado`.`Pessoa` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PortalVoluntariado`.`Habilidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortalVoluntariado`.`Habilidade` ;

CREATE TABLE IF NOT EXISTS `PortalVoluntariado`.`Habilidade` (
  `ID_Habilidade` INT(3) NOT NULL AUTO_INCREMENT,
  `Nome` TEXT(50) NULL,
  PRIMARY KEY (`ID_Habilidade`),
  UNIQUE INDEX `ID_Habilidade_UNIQUE` (`ID_Habilidade` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PortalVoluntariado`.`Pessoa-Habilidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortalVoluntariado`.`Pessoa-Habilidade` ;

CREATE TABLE IF NOT EXISTS `PortalVoluntariado`.`Pessoa-Habilidade` (
  `ID_Pessoa` INT(5) NOT NULL,
  `ID_Habilidade` INT(3) NOT NULL,
  PRIMARY KEY (`ID_Pessoa`, `ID_Habilidade`),
  INDEX `fk_Pessoa_has_Habilidade_Habilidade1_idx` (`ID_Habilidade` ASC),
  INDEX `fk_Pessoa_has_Habilidade_Pessoa1_idx` (`ID_Pessoa` ASC),
  CONSTRAINT `fk_Pessoa_has_Habilidade_Pessoa1`
    FOREIGN KEY (`ID_Pessoa`)
    REFERENCES `PortalVoluntariado`.`Pessoa` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_has_Habilidade_Habilidade1`
    FOREIGN KEY (`ID_Habilidade`)
    REFERENCES `PortalVoluntariado`.`Habilidade` (`ID_Habilidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PortalVoluntariado`.`Habilidade-Vaga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortalVoluntariado`.`Habilidade-Vaga` ;

CREATE TABLE IF NOT EXISTS `PortalVoluntariado`.`Habilidade-Vaga` (
  `ID_Vaga` INT(5) NOT NULL,
  `ID_Habilidade` INT(3) NOT NULL,
  PRIMARY KEY (`ID_Vaga`, `ID_Habilidade`),
  INDEX `fk_Habilidade_has_Vaga_Vaga1_idx` (`ID_Vaga` ASC),
  INDEX `fk_Habilidade_has_Vaga_Habilidade1_idx` (`ID_Habilidade` ASC),
  CONSTRAINT `fk_Habilidade_has_Vaga_Habilidade1`
    FOREIGN KEY (`ID_Habilidade`)
    REFERENCES `PortalVoluntariado`.`Habilidade` (`ID_Habilidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Habilidade_has_Vaga_Vaga1`
    FOREIGN KEY (`ID_Vaga`)
    REFERENCES `PortalVoluntariado`.`Vaga` (`ID_Vaga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PortalVoluntariado`.`Causa-Projeto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortalVoluntariado`.`Causa-Projeto` ;

CREATE TABLE IF NOT EXISTS `PortalVoluntariado`.`Causa-Projeto` (
  `ID_Projeto` INT(5) NOT NULL,
  `ID_Causa` INT(3) NOT NULL,
  PRIMARY KEY (`ID_Projeto`, `ID_Causa`),
  INDEX `fk_CausaDeInteresse_has_Projeto_Projeto1_idx` (`ID_Projeto` ASC),
  INDEX `fk_CausaDeInteresse_has_Projeto_CausaDeInteresse1_idx` (`ID_Causa` ASC),
  CONSTRAINT `fk_CausaDeInteresse_has_Projeto_CausaDeInteresse1`
    FOREIGN KEY (`ID_Causa`)
    REFERENCES `PortalVoluntariado`.`CausaDeInteresse` (`ID_Causa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CausaDeInteresse_has_Projeto_Projeto1`
    FOREIGN KEY (`ID_Projeto`)
    REFERENCES `PortalVoluntariado`.`Projeto` (`ID_Projeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PortalVoluntariado`.`Pontual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PortalVoluntariado`.`Pontual` ;

CREATE TABLE IF NOT EXISTS `PortalVoluntariado`.`Pontual` (
  `ID_Projeto` INT(5) NOT NULL,
  `ID_Vaga` INT(5) NOT NULL,
  `DataInicio` DATE NULL,
  `DataFim` DATE NULL,
  `PrazoParaInscricoes` DATE NULL,
  PRIMARY KEY (`ID_Projeto`, `ID_Vaga`),
  CONSTRAINT `fk_Pontual_Vaga1`
    FOREIGN KEY (`ID_Projeto` , `ID_Vaga`)
    REFERENCES `PortalVoluntariado`.`Vaga` (`ID_Projeto` , `ID_Vaga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
